Learning Howto - Reverse Proxy + custom URL + GSSAPI in war config
rundeck/docs pull request #1069
Opened 2022-08-25 20:26 UTC by AndLLA

Hallo,
I created a new pull request, as the previous one was closed.
https://github.com/rundeck/docs/pull/1061

I hope I followed the suggestion in the correct way.

Thanks

2022-08-25 20:49 UTC, fdevans requested changes
Had to make comments on minor changes that I'd normally handle myself, but GitHub won't let me edit your fork PR.  If you can make these small updates I'll pass it to the technical team to validate.

2022-08-25 20:49 UTC, fdevans commented on docs/.vuepress/sidebar-menus/learning.js
> +              '/learning/howto/apache2-proxy-gssapi.md',
remove trailing comma or the menus may not build successfully

2022-08-25 20:49 UTC, fdevans commented on docs/learning/howto/apache2-proxy-gssapi.md
> +* a valid keytab has been generated and contains the correct principal keys (in this case HTTP/srv.example.com@EXAMPLE.COM)
Capital A

2022-08-25 20:49 UTC, fdevans commented on docs/learning/howto/apache2-proxy-gssapi.md
> +This approach is very simple and perhaps suitable only for a small user base
This comment should likely go up at the top in the description of the article/solution.

2022-08-25 20:55 UTC, fdevans commented on docs/.vuepress/sidebar-menus/learning.js
> +              '/learning/howto/apache2-proxy-gssapi.md',
Did you happen to test the build?

2022-08-28 14:34 UTC, AndLLA commented
Hallo,
I fixed the typos and moved the comment to the introduction.
I tested the build (previously, and after the fixed) and it seems to work (note that I'm using the latest vuepress,
because some of the pinned dependencies seem to require python2, which I do not have anymore.

Thanks

![rundeck_docs_dev_run](https://user-images.githubusercontent.com/44858649/187079321-192e4ab8-6861-46f0-a0dc-24317aef1250.png)

2022-08-31 15:49 UTC, fdevans commented
Great, thank you.  @MegaDrive68k will help test the techincal bits and let us know his feedback soon.

2022-09-01 21:58 UTC, MegaDrive68k approved these changes
It works in my environment, all good :) Thank you @AndLLA

2022-09-01 22:04 UTC, fdevans approved these changes

2022-09-01 22:05 UTC, fdevans commented
@AndLLA If you can resolve the last bit of conflicts I can hopefully merge before our 4.6.0 release.

2022-09-02 05:46 UTC, AndLLA commented
Hallo,
the conflict should be fixed.

Thanks !!!

2022-09-02 08:03 UTC, fdevans approved these changes

2022-09-02 08:03 UTC, merged