Update advanced-run-job.md
rundeck/docs pull request #1135
Opened 2022-12-06 20:06 UTC by lcanavosio

added rundeck.feature.eventStore.enabled property in FAQs

2022-12-06 20:35 UTC, fdevans requested changes
we need blank lines between 259 and 260 and between the section header (currently 260) and the content (261)

2022-12-14 22:20 UTC, fdevans commented
We should also note if this can be set using Configuration Management using a custom setting for ENT customers.

2023-01-05 17:24 UTC, lcanavosio reviewed
for review

2023-01-06 17:42 UTC, fdevans approved these changes

2023-01-06 17:43 UTC, merged