Communityhow2
rundeck/docs pull request #1196
Opened 2023-03-16 17:51 UTC by wayfaringson

Two new Community How2 articles focused on deploying RD with Terraform on EKS and vanilla AWS.  Also includes updates to the glossary of terms to include terms for the upcoming Jobs 101 content.

2023-03-16 18:00 UTC, fdevans requested changes

2023-03-16 18:00 UTC, fdevans commented on docs/learning/howto/how2-terra-rd-aws.md
> +# Deploying Rundeck on AWS with Terraform
I think we should note that this works (or doesn't) on both OSS and Enterprise versions somewhere just for clarity.  In other docs we call our the two versions and highlight differences.

2023-03-16 18:00 UTC, fdevans commented on docs/learning/howto/how2-terra-rd-eks.md
> +# Deploying Rundeck on AWS EKS with Terraform
Same as other comment.  Identify whether this is Enterprise Only or available for OSS

2023-03-16 22:24 UTC, wayfaringson commented on docs/learning/howto/how2-terra-rd-aws.md
> +# Deploying Rundeck on AWS with Terraform
Just added updated language in both overviews that specifically include Process Automation as covered by these instructions

2023-03-23 23:37 UTC, fdevans approved these changes

2023-03-23 23:41 UTC, merged