Fixing broken link on k8s-logs-events.md
rundeck/docs pull request #1359
Opened 2023-10-18 20:36 UTC by t1agob

The suggested link to download the job definition yaml file is broken. Looks like the file was moved to a new location.

2023-10-18 22:08 UTC, fdevans commented
This is not the proper link to this.  If placing files in the `docs/.vuepress/assets/` directory the link text should read as follows:

`[text about link](/assets/text/sample_k8s_job.yaml)`

The Vuepress will handle the links properly from there.

2023-10-18 22:08 UTC, fdevans requested changes
See previous comment

2023-10-19 12:28 UTC, t1agob commented
Thanks for the feedback @fdevans. I wasn't aware the vuepress conventions. Updated now.

2023-10-19 16:29 UTC, fdevans approved these changes

2023-10-19 16:29 UTC, merged