Improve documentation to use ldaps with Rundeck 3.X
rundeck/docs pull request #421
Opened 2020-01-30 19:27 UTC by fgutierrezz

ldaps + rundeck (tested in Rundeck 3.0.26 PRO)

------ LINUX -------
1. Download the external certificate from remote server 
# echo -n | openssl s_client -connect ldapvb.cl:636 > certif.out
# keytool -importcert -trustcacerts -file certif.out -alias srvldap -keystore etc/truststore 

password: adminadmin

2. Import in rundeck
# keytool -importcert -trustcacerts -file certif.out -alias srvldap -keystore etc/truststore 

3. Import cert in JAVA HOME
keytool -importcert -trustcacerts -file certif.out -alias srvldap -keystore /usr/lib/jvm/jdk1.8.0_231/jre/lib/security/cacerts

password: 
changeit

------ WINDOWS -------
1. Download certificate from remote site 
c:\>  openssl s_client -connect ldaps_server.example:63 > C:\rundeck\certs.out

2. Import the file to keystore in Java home  . 
c:\> keytool -importcert -file "C:\rundeck\certs.out" -storepass changeit -keystore "C:\Program Files\Java\jre1.8.0_xxx\lib\security\cacerts" -alias host_ext

3. Import the file to keystore in rundeck . 
c:\> keytool -importcert -file "C:\rundeck\certs.out" -storepass adminadmin -keystore "C:\rundeck\etc\truststore" -alias ldapsserver

2020-02-12 18:26 UTC, jplassnibatt commented
@fgutierrezz could you please edit the "import in rundeck" step, so it is clear that this is only needed if rundeck is ssl too?

2020-02-12 20:48 UTC, fgutierrezz commented
updated

2020-02-12 21:01 UTC, jplassnibatt submitted a review, later dismissed

2020-02-26 15:02 UTC, jplassnibatt requested changes
typo in port, line 582

2020-02-26 15:24 UTC, jplassnibatt approved these changes
ok

2020-03-23 18:12 UTC, jessemarple approved these changes

2020-03-23 18:12 UTC, merged