Patch 2
rundeck/docs pull request #428
Opened 2020-02-12 18:13 UTC by cwaltherf

adding enabling Rundeck 3 with TLSv1 and Ciphers (limiting TLS protocols for ssl connections )

2020-02-12 18:27 UTC, ProTip commented
TLS `1.0` and `1.1` is effectively dead after March 2020; Chrome and Firefox have already removed support for it. I feel like _if_ we document this, we should put some warnings up about the security implications. @gschueler thoughts?

2020-02-12 18:29 UTC, gschueler commented
don't keep the rundeck 2 information, replace it with the correct rundeck 3 options `server.ssl.enabledProtocols` and `server.ssl.ciphers`.

don't include information on re-enabling TLSv1

2020-02-12 18:30 UTC, gschueler requested changes
don't keep the rundeck 2 information, replace it with the correct rundeck 3 options `server.ssl.enabledProtocols` and `server.ssl.ciphers`.

don't include information on re-enabling TLSv1

2020-02-12 20:14 UTC, jplassnibatt submitted a review, later dismissed

2020-02-12 20:51 UTC, gschueler requested changes

2020-02-12 20:51 UTC, gschueler commented on docs/administration/security/ssl.md
> +https://github.com/cwaltherf/docs/blob/patch-2/docs/administration/security/ssl.md
```suggestion
```

2020-02-12 20:51 UTC, gschueler commented on docs/administration/security/ssl.md
> +#### Create a Keystore file-Dserver.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
```suggestion
#### Create a Keystore file
```

2020-02-12 21:27 UTC, cwaltherf commented on docs/administration/security/ssl.md
> +https://github.com/cwaltherf/docs/blob/patch-2/docs/administration/security/ssl.md
done

2020-02-12 21:28 UTC, cwaltherf commented on docs/administration/security/ssl.md
> +#### Create a Keystore file-Dserver.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
done

2020-02-12 21:43 UTC, jplassnibatt approved these changes
some weird pasted links fixed

2020-02-13 00:25 UTC, gschueler approved these changes

2020-03-03 20:35 UTC, merged