Messaging cleanup
rundeck/docs pull request #881
Opened 2021-09-28 19:07 UTC by ronaveva

Add description of new messaging cleanup property when running on cluster mode

related to https://github.com/rundeckpro/rundeckpro/pull/2027

2021-09-29 15:19 UTC, fdevans requested changes

2021-09-29 15:19 UTC, fdevans commented on docs/administration/configuration/remote-job-execution.md
> +A property is available to set a timer to cleanup the remote execution messages when running on cluster mode. Unit of meassure is in minutes with a default value of '30', in order to change this valu
can we add context? Why would someone need to set this?

2021-09-29 16:31 UTC, ronaveva commented on docs/administration/configuration/remote-job-execution.md
> +A property is available to set a timer to cleanup the remote execution messages when running on cluster mode. Unit of meassure is in minutes with a default value of '30', in order to change this valu
done

2021-10-04 15:19 UTC, fdevans approved these changes

2021-10-04 15:19 UTC, merged