Learning solutions
rundeck/docs pull request #930
Opened 2022-02-16 21:54 UTC by jsboak

initial review of first Solution's how-to

2022-02-16 22:41 UTC, fdevans requested changes

2022-02-16 22:41 UTC, fdevans commented on docs/learning/solutions/auto-incident-kubernetes-logs.md
> +3. Download the sample Rundeck Job YAML from this [link](https://raw.githubusercontent.com/jsboak/rundeck_sandbox_scm/master/33ef389a-d45c-42d1-af56-3360ff0dade5.yaml?token=GHSAT0AAAAAABQRZMTKT4CBTPX
This should not come from your personal account.  Let's put it on the Community Welcome Project if we need a landing spot

2022-02-16 22:41 UTC, fdevans commented on docs/learning/solutions/auto-incident-kubernetes-logs.md
> +To optionally remove this expiration, so that API Tokens never expire, add a **Custom Config** property with `rundeck.api.tokens.duration.max`as the property name and set the value to `0`:
I don't think we should recommend this as it reduces the default security.  It's painful, but that's a choice they should make.

2022-02-24 19:56 UTC, jsboak commented
now has Community version of how-to and sample-job

2022-02-24 19:57 UTC, fdevans approved these changes

2022-02-24 19:57 UTC, merged